name: "Void Deploy Steam"
author: "Jake Gordon <jake@void.dev>"
description: "Deploy Void game to Steam"
inputs:
  releasePath:
    description: "path to packaged releases"
    default: "release"
    required: true
  executable:
    description: "executable name used when packaging game"
    default: "electron"
    required: true
  username:
    description: "A Steam username"
    required: true
  configVdf:
    description: "A steamcmd authorization config.vdf file (base64 encoded)"
    required: true
  appId:
    description: "A Steam Application ID"
    required: true
  windowsDepotId:
    description: "A Steam Depot ID to contain your Windows executable"
    required: false
  macosDepotId:
    description: "A Steam Depot ID to contain your MacOS excutable"
    required: false
  linuxDepotId:
    description: "A Steam Depot ID to contain your Linux executable"
    required: false
  buildDescription:
    description: "Description for this build"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    releasePath: ${{ inputs.releasePath }}
    executable: ${{ inputs.executable }}
    username: ${{ inputs.username }}
    configVdf: ${{ inputs.configVdf }}
    appId: ${{ inputs.appId }}
    windowsDepotId: ${{ inputs.windowsDepotId }}
    macosDepotId: ${{ inputs.macosDepotId }}
    linuxDepotId: ${{ inputs.linuxDepotId }}
    buildDescription: ${{ inputs.buildDescription }}
