name: "Void Deploy Steam"
author: "Jake Gordon <jake@void.dev>"
description: "Deploy Void game to Steam"
inputs:
  buildDescription:
    description: "Description for this build"
  executable:
    description: "executable file name prefix (not including extension)"
    default: "void"
  releasePath:
    description: "path to packaged releases"
    default: "release"
  username:
    description: "Steam username"
    required: true
  configVdf:
    description: "A steamcmd authorization config.vdf file (base64 encoded)"
    required: true
  appId:
    description: "Steam Application ID"
    required: true
  windowsDepotId:
    description: "Steam Depot ID for Windows binaries"
  macosDepotId:
    description: "Steam Depot ID for MacOS binaries"
  linuxDepotId:
    description: "Steam Depot ID for Linux binaries"
  setLiveBranch:
    description: "A custom Steam branch to set live with this build ('default' not allowed)"

runs:
  using: "docker"
  image: "docker://vaguevoid/deploy-steam:v1"
  env:
    buildDescription: ${{ inputs.buildDescription }}
    executable: ${{ inputs.executable }}
    releasePath: ${{ inputs.releasePath }}
    username: ${{ inputs.username }}
    configVdf: ${{ inputs.configVdf }}
    appId: ${{ inputs.appId }}
    windowsDepotId: ${{ inputs.windowsDepotId }}
    macosDepotId: ${{ inputs.macosDepotId }}
    linuxDepotId: ${{ inputs.linuxDepotId }}
    setLiveBranch: ${{ inputs.setLiveBranch }}
