name: "Void Package Electron"
author: "Jake Gordon <jake@void.dev>"
description: "Default Electron packager for Void games"
inputs:
  bundle:
    description: "path to your bundled web game"
    required: true
    default: "release/web"
  releasePath:
    description: "directory for packaged releases"
    default: "release"
    required: true
  executable:
    description: "executable file name prefix"
    required: true
    default: "electron"
  platform:
    description: "target platform" 
    required: true
    type: choice
    options:
      - win32
      - linux
      - darwin
  arch:
    description: "target architecture"
    required: true
    type: choice
    options:
      - x64
      - arm64
  electronVersion:
    description: "version of electron"
    required: true
    default: "31.0.2"
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    bundle: ${{ inputs.bundle }}
    releasePath: ${{ inputs.releasePath }}
    executable: ${{ inputs.executable }}
    platform: ${{ inputs.platform }}
    arch: ${{ inputs.arch }}
    electronVersion: ${{ inputs.electronVersion }}
