name: "Void Package Electron"
author: "Jake Gordon <jake@void.dev>"
description: "Default Electron packager for Void games"
inputs:
  dist:
    required: true
    default: "dist"
  platform:
    required: true
  arch:
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    DIST: ${{ inputs.path }}
    PLATFORM: ${{ inputs.platform }}
    ARCH: ${{ inputs.arch }}
