name: "Void Package Electron"
author: "Jake Gordon <jake@void.dev>"
description: "Default Electron packager for Void games"
inputs:
  prefix:
    description: "short name for your game that can be used as filename friendly prefix, e.g. snakes-on-steam"
    required: true
    default: "release"
  dist:
    description: "path to your bundled web game"
    required: true
    default: "dist"
  electronVersion:
    description: "version of electron to package the game"
    required: true
    default: "31.0.2"
  platform:
    description: "target platform (win32 | linux | darwin)"
    required: true
  arch:
    description: "target architecture (x64 | arm64)"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    prefix: ${{ inputs.prefix }}
    dist: ${{ inputs.dist }}
    electronVersion: ${{ inputs.electronVersion }}
    platform: ${{ inputs.platform }}
    arch: ${{ inputs.arch }}
