name: "Void Deploy to Web"
author: "Jake Gordon <jake@void.dev>"
description: "Deploy Void game to the Web at play.void.dev"
inputs:
  host:
    description: "web host url"
    default: "https://play.void.dev/"
    required: true
  path:
    description: "path to built game assets"
    default: "release/web"
    required: true
  organization:
    description: "your play.void.dev organization name"
    required: true
  game:
    description: "your play.void.dev game name"
    required: true
  label:
    description: "build label"
    required: true
  token:
    description: "your Void personal access token"
    required: true
  password:
    description: "(optional) password protect your shared game"
    required: false
  pinned:
    description: "(optional) true | false to pin deploy and prevent auto expiration and deletion"
    default: "false"
    required: false

runs:
  using: "docker"
  image: "docker://vaguevoid/deploy-web:v1"
  env:
    host: ${{ inputs.host }}
    path: ${{ inputs.path }}
    organization: ${{ inputs.organization }}
    game: ${{ inputs.game }}
    label: ${{ inputs.label }}
    token: ${{ inputs.token }}
    password: ${{ inputs.password }}
    pinned: ${{ inputs.pinned }}

