name: "Share a Void game on Steam"
author: "Jake Gordon <jake@void.dev>"
description: "Build, Package, and Deploy a Void game to Steam"
inputs:
  buildTask:
    description: "(optional) bun task to build the game"
    required: false
    default: "build"
  buildDescription:
    description: "Description for this build"
  executable:
    description: "executable file name prefix (not including extension)"
    default: "void"
  releasePath:
    description: "path to packaged releases"
    default: "release"
  baseUrl:
    description: "base URL"
    default: "./"
  username:
    description: "Steam user name"
    required: true
  configVdf:
    description: "A steamcmd authorization config.vdf file (base64 encoded)"
    required: true
  appId:
    description: "Steam Application ID"
    required: true
  windowsDepotId:
    description: "Steam Depot ID for Windows binaries"
  macosDepotId:
    description: "Steam Depot ID for MacOS binaries"
  linuxDepotId:
    description: "Steam Depot ID for Linux binaries"
  setLiveBranch:
    description: "A custom Steam branch to set live with this build ('default' not allowed)"
  compressTextures:
    description: "true | false to enable texture packing"
    default: "false"
  textureFormat:
    description: "format for compressed textures (DXT or KTX)"
    type: choice
    options:
      - "DXT"
      - "KTX"
    default: "DXT"
  ignoreTextures:
    description: "(optional) space separated list of images (or directories) to be ignored by texture packer"
    default: "favicon.png"
  textureThreads:
    description: "(optional) thread count for image compressor (use 4 for standard GitHub Runner)"
    default: 4

runs:
  using: "composite"
  steps:
    - name: "Build"
      uses: "vaguevoid/actions/build/vite@alpha"
      with:
        buildTask: ${{ inputs.buildTask }}
        output: ${{ inputs.releasePath }}/web
        baseUrl: ${{ inputs.baseUrl }}
        deployTarget: "steam"

    - name: "Package Textures"
      uses: "vaguevoid/actions/package/textures@alpha"
      if: ${{ inputs.compressTextures == 'true' }}
      with:
        path: ${{ inputs.releasePath }}/web
        format: ${{ inputs.textureFormat }}
        ignore: ${{ inputs.ignoreTextures }}
        threads: ${{ inputs.textureThreads }}

    - name: "Package for Windows"
      uses: "vaguevoid/actions/package/electron@alpha"
      if: ${{ inputs.windowsDepotId != '' }}
      with:
        bundle: ${{ inputs.releasePath }}/web
        releasePath: ${{ inputs.releasePath }}
        executable: ${{ inputs.executable }}
        platform: win32
        arch: x64

    - name: "Package for MacOS"
      uses: "vaguevoid/actions/package/electron@alpha"
      if: ${{ inputs.macosDepotId != '' }}
      with:
        bundle: ${{ inputs.releasePath }}/web
        releasePath: ${{ inputs.releasePath }}
        executable: ${{ inputs.executable }}
        platform: darwin
        arch: x64

    - name: "Package for Linux"
      uses: "vaguevoid/actions/package/electron@alpha"
      if: ${{ inputs.linuxDepotId != '' }}
      with:
        bundle: ${{ inputs.releasePath }}/web
        releasePath: ${{ inputs.releasePath }}
        executable: ${{ inputs.executable }}
        platform: linux
        arch: x64

    - name: "Deploy"
      uses: "vaguevoid/actions/deploy/steam@alpha"
      with:
        buildDescription: ${{ inputs.buildDescription }}
        executable: ${{ inputs.executable }}
        releasePath: ${{ inputs.releasePath }}
        username: ${{ inputs.username }}
        configVdf: ${{ inputs.configVdf }}
        appId: ${{ inputs.appId }}
        windowsDepotId: ${{ inputs.windowsDepotId }}
        macosDepotId: ${{ inputs.macosDepotId }}
        linuxDepotId: ${{ inputs.linuxDepotId }}
        setLiveBranch: ${{ inputs.setLiveBranch }}
