name: "Share a Void game on the web at play.void.dev"
author: "Jake Gordon <jake@void.dev>"
description: "Build, Package, and Deploy a Void game to the Web"
inputs:
  buildTask:
    description: "(optional) bun task to build the game"
    required: false
    default: "build"
  host:
    description: "web host url"
    default: "https://play.void.dev/"
    required: true
  organization:
    description: "your play.void.dev organization name"
    required: true
  game:
    description: "your play.void.dev game name"
    required: true
  label:
    description: "(optional) build label - branch name will be used by default"
    required: false
  token:
    description: "your Void personal access token"
    required: true
  password:
    description: "(optional) password protect your shared game"
    required: false
  pinned:
    description: "(optional) true | false to pin deploy and prevent auto expiration and deletion"
    required: false
    default: "false"
  outDir:
    description: "output directory for build assets generated by build step"
    required: false
    default: "dist"
  compressTextures:
    description: "true | false to enable texture packing"
    default: "false"
  textureFormat:
    description: "format for compressed textures (DXT or KTX)"
    type: choice
    options:
      - "DXT"
      - "KTX"
    default: "DXT"
  ignoreTextures:
    description: "(optional) space separated list of images (or directories) to be ignored by texture packer"
    default: "favicon.png"
  textureThreads:
    description: "(optional) thread count for image compressor (use 4 for standard GitHub Runner)"
    default: 4

runs:
  using: "composite"
  steps:
    - name: "Build"
      uses: "vaguevoid/actions/build/vite@v1"
      with:
        taskName: ${{ inputs.buildTask }}
        deployTarget: "play.void.dev"

    - name: "Package Textures"
      uses: "vaguevoid/actions/package/textures@v1"
      if: ${{ inputs.compressTextures == 'true' }}
      with:
        path: ${{ inputs.outDir }}
        format: ${{ inputs.textureFormat }}
        ignore: ${{ inputs.ignoreTextures }}
        threads: ${{ inputs.textureThreads }}

    - name: Get default deploy label
      uses: vaguevoid/actions/deploy/label@v1
      id: default_label

    - name: "Deploy"
      uses: "vaguevoid/actions/deploy/web@v1"
      with:
        path: ${{ inputs.outDir }}
        host: ${{ inputs.host }}
        organization: ${{ inputs.organization }}
        game: ${{ inputs.game }}
        label: ${{ inputs.label || steps.default_label.outputs.label }}
        token: ${{ inputs.token }}
        password: ${{ inputs.password }}
        pinned: ${{ inputs.pinned }}
