name: "Void Package Textures"
author: "Jake Gordon <jake@void.dev>"
description: "Default texture packager for Void games"
inputs:
  path:
    description: "path to your bundled web game"
    default: "release/web"
  format:
    description: "format for compressed textures (DXT or KTX)"
    type: choice
    options:
     - "DXT"
     - "KTX"
    default: "DXT"
  ignore:
    description: "(optional) space separated list of textures (or directories) to be ignored"
    default: "favicon.png"
runs:
  using: "docker"
  image: "docker://vaguevoid/package-textures:latest"
  env:
    path: ${{ inputs.path }}
    format: ${{ inputs.format }}
    ignore: ${{ inputs.ignore }}
